#!/bin/sh

#java -jar AlignerBooster-v1.1.jar run stratumSE --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test1_hg19_filtered.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test1_hg19_best.bam
#java -jar AlignerBooster-v1.1.jar run stratumSE --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test2_hg19_filtered.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test2_hg19_best.bam
#java -jar AlignerBooster-v1.1.jar run stratumSE --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test3_hg19_filtered.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test3_hg19_best.bam
#java -jar AlignerBooster-v1.1.jar run stratumSE --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test4_hg19_filtered.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test4_hg19_best.bam
#java -jar AlignerBooster-v1.1.jar run stratumSE --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test5_hg19_filtered.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test5_hg19_best.bam
#java -jar AlignerBooster-v1.1.jar run stratumSE --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test6_hg19_filtered.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test6_hg19_best.bam
#java -jar AlignerBooster-v1.1.jar run stratumSE --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test7_hg19_filtered.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test7_hg19_best.bam
#java -jar AlignerBooster-v1.1.jar run stratumSE --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test8_hg19_filtered.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test8_hg19_best.bam
