#!/bin/sh

#java -jar AlignerBooster-v1.1.jar run filterSE --min-insert 15 --seed-len 25 --seed-mis 4.0 --all-mis 6.0 --all-indel 0.0 --1DP   --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test1_hg19_raw.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test1_hg19_filtered.bam
#java -jar AlignerBooster-v1.1.jar run filterSE --min-insert 15 --seed-len 25 --seed-mis 4.0 --all-mis 6.0 --all-indel 0.0   --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test2_hg19_raw.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test2_hg19_filtered.bam
#java -jar AlignerBooster-v1.1.jar run filterSE --min-insert 15 --seed-len 25 --seed-mis 4.0 --all-mis 6.0 --all-indel 0.0   --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test3_hg19_raw.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test3_hg19_filtered.bam
#java -jar AlignerBooster-v1.1.jar run filterSE --min-insert 15 --seed-len 25 --seed-mis 4.0 --all-mis 6.0 --all-indel 0.0   --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test4_hg19_raw.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test4_hg19_filtered.bam
#java -jar AlignerBooster-v1.1.jar run filterSE --min-insert 15 --seed-len 25 --seed-mis 4.0 --all-mis 6.0 --all-indel 0.0   --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test5_hg19_raw.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test5_hg19_filtered.bam
#java -jar AlignerBooster-v1.1.jar run filterSE --min-insert 15 --seed-len 25 --seed-mis 4.0 --all-mis 6.0 --all-indel 0.0   --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test6_hg19_raw.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test6_hg19_filtered.bam
#java -jar AlignerBooster-v1.1.jar run filterSE --min-insert 15 --seed-len 25 --seed-mis 4.0 --all-mis 6.0 --all-indel 0.0   --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test7_hg19_raw.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test7_hg19_filtered.bam
#java -jar AlignerBooster-v1.1.jar run filterSE --min-insert 15 --seed-len 25 --seed-mis 4.0 --all-mis 6.0 --all-indel 0.0   --max-div 4.0 --max-best 0 --max-report 10 -in /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test8_hg19_raw.bam -out /home/zhengqi/git/AlignerBoost/AlignerBoost/test/human_test8_hg19_filtered.bam
